name: ypdf

services:
  account_api:
    build:
      context: .
      dockerfile: ./Services/Ypdf.Web.AccountAPI/Dockerfile
    container_name: AccountAPI
    depends_on:
      - accounts_database
    expose:
      - 8081
    ports:
      - 8081:443
    restart: always
    environment:
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/localhost.key
    volumes:
      - ./Certificates:/https

  pdf_processing_api:
    build:
      context: .
      dockerfile: ./Services/Ypdf.Web.PdfProcessingAPI/Dockerfile
    container_name: PdfProcessingAPI
    depends_on:
      - rabbitmq
    expose:
      - 8082
    ports:
      - 8082:443
    restart: always
    environment:
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: Ypdf
      RABBITMQ_PASSWORD: Ypdf2025
      ASPNETCORE_HTTPS_PORT: 8082
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/localhost.key
    volumes:
      - ./Certificates:/https
      - output_files:/output

  pdf_operations_history_api:
    build:
      context: .
      dockerfile: ./Services/Ypdf.Web.PdfOperationsHistoryAPI/Dockerfile
    container_name: PdfOperationsHistoryAPI
    depends_on:
      - rabbitmq
    expose:
      - 8083
    ports:
      - 8083:443
    restart: always
    environment:
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_ENVIRONMENT: Development
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: Ypdf
      RABBITMQ_PASSWORD: Ypdf2025
      ASPNETCORE_HTTPS_PORT: 8083
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.crt
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /https/localhost.key
    volumes:
      - ./Certificates:/https
      - db_data:/db

  accounts_database:
    image: postgis/postgis:13-master
    container_name: AccountsDbPostgres
    expose:
      - 8080
    ports:
      - 8080:5432
    restart: always
    environment:
      POSTGRES_USER: Ypdf
      POSTGRES_PASSWORD: Ypdf2025
      POSTGRES_MULTIPLE_DATABASES: AccountsDB
    volumes:
      - ./Docker/Postgres:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: Ypdf
      RABBITMQ_DEFAULT_PASS: Ypdf2025

volumes:
  db_data:
  output_files:
