apiVersion: v1
kind: Service
metadata:
  name: accounts-database
  namespace: ypdf
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8080
      targetPort: 5432
  selector:
    app: accounts-database
