apiVersion: v1
kind: Service
metadata:
  name: files-api
  namespace: ypdf
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 8082
      targetPort: 443
      nodePort: 32082
  selector:
    app: files-api
