apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - tls-secret.yml
  - accounts-database-pvc.yml
  - db-data-pvc.yml
  - intput-files-pvc.yml
  - output-files-pvc.yml

resources:
  - accounts-database-deployment.yml
  - accounts-database-service.yml
  - rabbitmq-deployment.yml
  - rabbitmq-service.yml

resources:
  - account-api-deployment.yml
  - files-api-deployment.yml
  - pdf-processing-api-deployment.yml
  - pdf-operations-history-api-deployment.yml
  - web-app-deployment.yml

resources:
  - account-api-service.yml
  - files-api-service.yml
  - pdf-processing-api-service.yml
  - pdf-operations-history-api-service.yml
  - web-app-service.yml

resources:
  - pdf-processing-api-hpa.yml

