apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-processing-api-hpa
  namespace: ypdf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-processing-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1
