apiVersion: v1
kind: Service
metadata:
  name: account-api
  namespace: ypdf
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8081
      targetPort: 443
  selector:
    app: account-api
