apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: ypdf
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 9001
      targetPort: 443
      nodePort: 32001
  selector:
    app: web-app
