apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  namespace: ypdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-api
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
      - name: account-api
        image: ypdf-account-api:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 443
        env:
          - name: ASPNETCORE_URLS
            value: "https://+;http://+"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_HTTPS_PORT
            value: "443"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "/https/tls.crt"
          - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
            value: "/https/tls.key"
          - name: Jwt__Key
            valueFrom:
              secretKeyRef:
                name: secret-jwt
                key: JWT_KEY
          - name: ConnectionStrings__Accounts
            valueFrom:
              secretKeyRef:
                name: secret-accounts-database
                key: ACCOUNTS_DATABASE_CONNECTION_STRING
          - name: InitialUsers__Admin__Email
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: ADMIN_USER_EMAIL
          - name: InitialUsers__Admin__UserName
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: ADMIN_USER_USERNAME
          - name: InitialUsers__Admin__Nickname
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: ADMIN_USER_NICKNAME
          - name: InitialUsers__Admin__Password
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: ADMIN_USER_PASSWORD
          - name: InitialUsers__TestUser__Email
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: TEST_USER_EMAIL
          - name: InitialUsers__TestUser__UserName
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: TEST_USER_USERNAME
          - name: InitialUsers__TestUser__Nickname
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: TEST_USER_NICKNAME
          - name: InitialUsers__TestUser__Password
            valueFrom:
              secretKeyRef:
                name: secret-initial-users
                key: TEST_USER_PASSWORD
        volumeMounts:
          - name: tls-certificates
            mountPath: /https
      volumes:
        - name: tls-certificates
          secret:
            secretName: secret-tls
      resources:
        limits:
          cpu: "200m"
          memory: "400Mi"
        requests:
          cpu: "100m"
          memory: "300Mi"
