apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-operations-history-api
  namespace: ypdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-operations-history-api
  template:
    metadata:
      labels:
        app: pdf-operations-history-api
    spec:
      containers:
      - name: pdf-operations-history-api
        image: ypdf-pdf-operations-history-api:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 443
        env:
          - name: ASPNETCORE_URLS
            value: "https://+;http://+"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_HTTPS_PORT
            value: "8083"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "/https/tls.crt"
          - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
            value: "/https/tls.key"
          - name: Jwt__Key
            valueFrom:
              secretKeyRef:
                name: secret-jwt
                key: JWT_KEY
          - name: RabbitMq__HostName
            value: "rabbitmq"
          - name: RabbitMq__UserName
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: RABBITMQ_USER
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                name: secret-rabbitmq
                key: RABBITMQ_PASSWORD
        volumeMounts:
          - name: tls-certificates
            mountPath: /https
          - name: db-data
            mountPath: /db
      volumes:
        - name: tls-certificates
          secret:
            secretName: secret-tls
        - name: db-data
          persistentVolumeClaim:
            claimName: pvc-db-data
      resources:
        limits:
          cpu: "200m"
          memory: "400Mi"
        requests:
          cpu: "100m"
          memory: "300Mi"
