apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-database
  namespace: ypdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-database
  template:
    metadata:
      labels:
        app: accounts-database
    spec:
      containers:
      - name: accounts-database
        image: postgis/postgis:13-master
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-accounts-database
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-accounts-database
                key: POSTGRES_PASSWORD
          - name: POSTGRES_MULTIPLE_DATABASES
            value: "AccountsDB"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: accounts-database-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: accounts-database-data
          persistentVolumeClaim:
            claimName: pvc-accounts-database
      resources:
        limits:
          cpu: "2000m"
          memory: "512Mi"
        requests:
          cpu: "500m"
          memory: "256Mi"
