apiVersion: v1
kind: Service
metadata:
  name: pdf-operations-history-api
  namespace: ypdf
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 8083
      targetPort: 443
      nodePort: 32083
  selector:
    app: pdf-operations-history-api
