apiVersion: v1
kind: Service
metadata:
  name: pdf-processing-api
  namespace: ypdf
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 8084
      targetPort: 443
      nodePort: 32084
  selector:
    app: pdf-processing-api
