apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: ypdf
  labels:
    app: rabbitmq-exporter
spec:
  ports:
  - name: metrics
    port: 9419
    targetPort: 9419
  selector:
    app: rabbitmq-exporter
